#!/bin/bash
sudo pacman -Syu --noconfirm
sudo pacman -S --noconfirm bind
sudo pacman -S --noconfirm clamtk
sudo pacman -S --noconfirm copyq
sudo pacman -S --noconfirm dkms
sudo pacman -S --noconfirm docker
sudo pacman -S --noconfirm libreoffice-fresh
sudo pacman -S --noconfirm dolphin
sudo pacman -S --noconfirm firefox
sudo pacman -S --noconfirm discord
sudo pacman -S --noconfirm pcmanfm
sudo pacman -S --noconfirm fish
sudo pacman -S --noconfirm galculator
sudo pacman -S --noconfirm gimp
sudo pacman -S --noconfirm gitkraken
sudo pacman -S --noconfirm grimblast-git
sudo pacman -S --noconfirm htop
sudo pacman -S --noconfirm kvantum-git
sudo pacman -S --noconfirm mpv
sudo pacman -S --noconfirm swappy
sudo pacman -S --noconfirm rclone
sudo pacman -S --noconfirm neofetch
sudo pacman -S --noconfirm nnn
sudo pacman -S --noconfirm nodejs
sudo pacman -S --noconfirm npm
sudo pacman -S --noconfirm nvm
sudo pacman -S --noconfirm obs-studio
sudo pacman -S --noconfirm obsidian
sudo pacman -S --noconfirm octopi
sudo pacman -S --noconfirm pamac-aur
sudo pacman -S --noconfirm pnpm
sudo pacman -S --noconfirm postman-bin
sudo pacman -S --noconfirm psensor
sudo pacman -S --noconfirm python-fuzzywuzzy
sudo pacman -S --noconfirm python-pip
sudo pacman -S --noconfirm qt5ct
sudo pacman -S --noconfirm rofi
sudo pacman -S --noconfirm stacer
sudo pacman -S --noconfirm ttf-ms-fonts
sudo pacman -S --noconfirm ttf-jetbrains-mono
sudo pacman -S --noconfirm udiskie
sudo pacman -S --noconfirm ulauncher
sudo pacman -S --noconfirm visual-studio-code-bin
sudo pacman -S --noconfirm yarn
sudo pacman -S --noconfirm yay
sudo pacman -S --noconfirm wlsunset
sudo pacman -S --noconfirm wpaperd
sudo pacman -S --noconfirm google-chrome
sudo pacman -S --noconfirm wmctrl
sudo pacman -S --noconfirm xdotool
sudo pacman -S --noconfirm wev
sudo pacman -S --noconfirm jetbrains-toolbox
sudo pacman -S --noconfirm github-cli
sudo pacman -S --noconfirm the_silver_searcher
sudo pacman -Syu --noconfirm
